Update codegen plugins
SpineEventEngine/Chords pull request #61
Opened 2024-10-16 18:16 UTC by Oleg-Melnik

2024-10-18 15:05 UTC, armiol requested changes
@Oleg-Melnik LGTM except for a few comments.

2024-10-18 15:05 UTC, armiol commented on codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageDefFileGenerator.kt
> +        "UNCHECKED_CAST"
I would be very nice to generate a comment like we do for each suppression.

2024-10-18 15:05 UTC, armiol commented on codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageFieldObjectGenerator.kt
> +            .addAnnotation(buildGeneratedAnnotation())
Can we shorten all `build...` names, so that this whole section reads as follows:

```kotlin
return TypeSpec
            .objectBuilder(messageFieldClassName)
            .addSuperinterface(superinterface)
            .addAnnotation(generatedAnnotation())
            .addKdoc(buildKDoc(field))
            .addProperty(theNameProperty(field))
            .addProperty(theRequiredProperty(field))
            .addProperty(theDescriptorProperty(field))
            .addFunction(theValueInFunction(field))
            .addFunction(theHasValueFunction(field))
            .addFunction(theSetValueFunction(field))
            .build()
```

Perhaps, `the` part could also be truncated. I don't get the idea, honestly, but maybe it's just me :)

2024-10-19 23:44 UTC, Oleg-Melnik commented on codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageDefFileGenerator.kt
> +        "UNCHECKED_CAST"
There is no way to add a custom comment except in the function body, so I decided to generate the code without such warnings.

2024-10-19 23:54 UTC, Oleg-Melnik commented on codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageDefFileGenerator.kt
> +        "UNCHECKED_CAST"
Before:
```
private val fieldMap: Map<Int, MessageField<TestCommand, Any>> = mapOf(
        5 to TestCommandDef.oneOfOption1 as MessageField<TestCommand, Any>,
        6 to TestCommandDef.oneOfOption2 as MessageField<TestCommand, Any>,
        7 to TestCommandDef.oneOfOption3 as MessageField<TestCommand, Any>
)
```
After:
```
private val fieldMap: Map<Int, MessageField<TestCommand, Any>> = mapOf(
        5 to TestCommandDef.oneOfOption1.safeCast<MessageField<TestCommand, Any>>()!!,
        6 to TestCommandDef.oneOfOption2.safeCast<MessageField<TestCommand, Any>>()!!,
        7 to TestCommandDef.oneOfOption3.safeCast<MessageField<TestCommand, Any>>()!!
)

public inline fun <reified T: Any> Any.safeCast() : T? {
    return if (this is T) this else null
}

```

2024-10-20 14:24 UTC, armiol commented on codegen/plugins/codegen-plugins/src/main/kotlin/io/spine/chords/codegen/plugins/MessageDefFileGenerator.kt
> +        "UNCHECKED_CAST"
@Oleg-Melnik Let's look at the resulting code once it is generated. I mean, after it's merged.

2024-10-20 14:24 UTC, armiol approved these changes

2024-10-20 14:44 UTC, merged