Implement `Dialog` and `CommandDialog`
SpineEventEngine/Chords pull request #68
Opened 2024-10-30 10:11 UTC by Oleg-Melnik

This PR updates the project by adding a base class for dialogs, along with a specific implementation that supports editing and sending command messages.

The implemented classes are analogous to `Wizard` and `CommandWizard`, but contain a single page for editing data.

2024-10-30 11:20 UTC, armiol requested changes
@Oleg-Melnik please see my comments.

2024-10-30 11:20 UTC, armiol commented on client/src/main/kotlin/io/spine/chords/client/layout/CommandDialog.kt
> +     * A function that should be implemented to create and return a new builder
Here and in all similar places, let's shorten the descriptions, so that they conform to the standards we have. E.g.

```
Creates a builder for the command message of type [M].

May pre-fill the builder with the default values, 
or those required in terms of the domain language,
but not available for modification within the dialog UI.
```

2024-10-30 11:20 UTC, armiol commented on client/src/main/kotlin/io/spine/chords/client/layout/CommandDialog.kt
> + * A kind of [Dialog], which allows creating a command message and sending
Similarly to my comment below.
```
A [Dialog] designed to create or modify command messages,
and send the respective commands upon finish.
```

2024-10-30 11:20 UTC, armiol commented on client/src/main/kotlin/io/spine/chords/client/layout/CommandDialog.kt
> + * To create a concrete dialog you need to extend the class and override
I guess, this is obvious from the signature.

2024-10-30 11:20 UTC, armiol commented on client/src/main/kotlin/io/spine/chords/client/layout/CommandDialog.kt
> +                verticalArrangement = Arrangement.spacedBy(16.dp),
Let's discuss what happens if someone wants a different spacing.

2024-10-30 11:20 UTC, armiol commented on client/src/main/kotlin/io/spine/chords/client/layout/CommandDialog.kt
> +    override suspend fun submitForm(): Boolean {
Is it `public`? 

Please check whether the explicit API mode is enabled for the module.

2024-10-30 11:20 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/layout/Dialog.kt
> + * To create a concrete dialog you need to extend the class and override
Same as above.

2024-10-30 14:40 UTC, dpikhulya reviewed
@Oleg-Melnik Please see some comments below.

2024-10-30 17:07 UTC, armiol commented on client/src/main/kotlin/io/spine/chords/client/layout/CommandDialog.kt
> +                verticalArrangement = Arrangement.spacedBy(16.dp),
@dpikhulya @Oleg-Melnik 

I am not suggesting to figure out the grand-approach on dealing with issues like these, right now. Instead, I am saying that implanting ad-hoc styles into a common and generic component does not look good, since it's just a technical debt we would be dealing in the nearest future. Meaning, right in the next app (besides the one we already have) the spacing might be different, and we'll have to react immediately.

@dpikhulya 
The approach with two-level settings seems reasonable. However, I would try to understand what other UI libraries do in this case. E.g., the first one I opened had [that](https://github.com/epicarchitect/epic-calendar?tab=readme-ov-file#basis-calendar-setup).

2024-10-31 09:12 UTC, Oleg-Melnik commented on client/src/main/kotlin/io/spine/chords/client/layout/CommandDialog.kt
> +                verticalArrangement = Arrangement.spacedBy(16.dp),
@armiol @dpikhulya 

Currently, all dialog padding is implemented according to the [Material Design spec](https://m3.material.io/components/dialogs/specs#7dbad5e0-f001-4eae-a536-694aeca90ba6). However, that doesn’t mean we shouldn’t allow customization — I would make it.

Overall, I agree with the general approach: make maximum use of theme settings and, in addition, add the ability to customize a specific component.

Let's finish the discussion in the meeting.

2024-11-04 15:40 UTC, dpikhulya approved these changes
@Oleg-Melnik LGTM in general. I've only left one naming-related concern to consider.

2024-11-04 15:41 UTC, armiol requested changes
@Oleg-Melnik please see my comments.

2024-11-04 15:41 UTC, armiol commented on client/src/main/kotlin/io/spine/chords/client/layout/CommandDialog.kt
> + * and send the respective commands upon finish.
I would use "post" instead of "send". For "a command", "to post" is a more precise verb.

Another thing is that we only allow posting a single command from a single dialog. So I would be clear about that.
People _may_ want to send multiple commands from a single dialog. But that's not something we support at the moment (and I don't think we should, ever).

2024-11-04 15:41 UTC, armiol commented on client/src/main/kotlin/io/spine/chords/client/layout/CommandDialog.kt
> +                verticalArrangement = Arrangement.spacedBy(16.dp),
@Oleg-Melnik Here, it is still 
```kotlin
Arrangement.spacedBy(16.dp),
```

Maybe I don't understand something, but I thought we agreed on creating the configuration object instead. And yes, it should probably have `16.dp` as a default value—as per the spec. But it should be the default value of the configuration object. Not a hard-coded value in the code.

2024-11-04 15:54 UTC, Oleg-Melnik commented on client/src/main/kotlin/io/spine/chords/client/layout/CommandDialog.kt
> +                verticalArrangement = Arrangement.spacedBy(16.dp),
My mistake — I forgot to update the `CommandDialog`.

2024-11-04 16:44 UTC, Oleg-Melnik commented on client/src/main/kotlin/io/spine/chords/client/layout/CommandDialog.kt
> + * and send the respective commands upon finish.
I'll think about it.

2024-11-05 10:27 UTC, armiol approved these changes

2024-11-05 10:27 UTC, merged