Add companion object for `PaymentMethodEditor`
SpineEventEngine/Chords pull request #71
Opened 2024-11-03 21:55 UTC by dpikhulya

This PR introduces a class for creating companion objects of custom `MessageForm` implementations, and reworks companion objects of `MessageForm` and `CommandMessageForm` to reuse respective code with it.

2024-11-04 13:22 UTC, armiol requested changes
@dpikhulya please review your PR yourself one more time.

Please see my comments.

2024-11-04 13:22 UTC, armiol commented on dependencies.md
> +# Dependencies of `io.spine.chords:spine-chords-client:2.0.0-SNAPSHOT.40`
It cannot be this way. You cannot downgrade versions.

2024-11-04 13:22 UTC, armiol commented on proto/src/main/kotlin/io/spine/chords/proto/money/PaymentMethodEditor.kt
> +     *
?

2024-11-04 21:53 UTC, dpikhulya commented
@armiol I've made some more minor revisions. Seems to look fine for me.

2024-11-05 10:34 UTC, armiol requested changes
@dpikhulya Mostly LGTM. Please see my comments.

2024-11-05 10:34 UTC, armiol commented on proto/src/main/kotlin/io/spine/chords/proto/form/MessageForm.kt
> +    internal var onBeforeBuild: (ValidatingBuilder<out M>) -> Unit = {}
I noticed a lot of members had changed their visibility to `internal`. It means they will not be accessible to the sub-types.

Was that a design intention? And if so, please mention it in the PR description.

2024-11-05 10:34 UTC, armiol commented on proto/src/main/kotlin/io/spine/chords/proto/form/OneofRadioButton.kt
> +                        // selectedField treats all fields as MessageFieldValue
```
`selectedField` treats all fields as `MessageFieldValue`.
```

2024-11-05 10:34 UTC, armiol commented on proto/src/main/kotlin/io/spine/chords/proto/money/PaymentMethodEditor.kt
> +     * A component instance declaration API.
This hardly tell anything, I am afraid.

Please adjust the description, so that it helps readers.

2024-11-05 10:34 UTC, armiol commented on client/src/main/kotlin/io/spine/chords/client/form/CommandMessageForm.kt
>       * Form instance declaration and creation API.
See my another comment on the similar piece.

2024-11-05 18:11 UTC, dpikhulya commented on proto/src/main/kotlin/io/spine/chords/proto/form/MessageForm.kt
> +    internal var onBeforeBuild: (ValidatingBuilder<out M>) -> Unit = {}
@armiol Yes that was intentional. I've documented the respective reasining in the PR.

2024-11-05 19:02 UTC, armiol approved these changes

2024-11-05 19:04 UTC, merged