Implement handling of command rejections
SpineEventEngine/Chords pull request #86
Opened 2024-12-14 16:21 UTC by dpikhulya

2024-12-17 09:15 UTC, armiol commented
@dpikhulya 
Let me suggest an alternative approach:

```kotlin
  val command: SomeCommand = someCommand()
    val succeeded: Boolean = command.post(
        SubscribeTo({
            events<ExpectedEvent>(
                ExpectedEvent.Field.id(),
                command.id
            ),
            rejections<PossibleRejection>(
                PossibleRejection.Field.id(),
                command.id
            ) handledAs { ... }
        })
    )
```
Notice the change in wording. And also, the generic parameter (what you can infer in Kotlin, AFAIK), instead of the first argument.

Do I understand correctly that the subscription by any field (not just by `Field.id()` is assumed?

2024-12-17 09:17 UTC, armiol commented
@dpikhulya another question is why we have this duality in your code:
```kotlin

rejection( ... ) handledAs { ... }
// ...
// and then suddenly, again
onRejection { ... }
```
To me this looks like two ways to do the same. And this is somewhat confusing.

2024-12-17 09:17 UTC, armiol requested changes
@dpikhulya please see my comments.

2025-02-11 20:07 UTC, dpikhulya commented
@armiol PTAL

2025-02-12 14:26 UTC, merged