Integrate Voyager
SpineEventEngine/Chords pull request #87
Opened 2024-12-16 08:13 UTC by Oleg-Melnik

2024-12-23 12:57 UTC, armiol requested changes
@Oleg-Melnik 6/14 reviewed so far. Please see my comments. Also, as soon as this change is massive in terms of API changes, please expand the PR description so that "before" and "after" are clearer for readers.

2024-12-23 12:57 UTC, armiol commented on buildSrc/src/main/kotlin/io/spine/internal/dependency/Voyager.kt
> +    private const val baseName = "voyager"
Just `name` is enough, given this is a private const.

2024-12-23 12:57 UTC, armiol commented on core/build.gradle.kts
> +    implementation(Voyager.navigator)
If we expect end-users to have access to Voyager's API, this should also be `api`. `implementation` does not make the referenced library a transitive dependency.

Please review.

2024-12-23 12:57 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/appshell/AppView.kt
> +) : Component(), Screen
Given this API addition, I would expect at least something to change in the type's documentation.

2024-12-23 12:57 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
> +     * An instance of the screens [Navigator] that will be initialized during
"screens"? Plural?

Please review.

2024-12-23 12:57 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
> +        keepCurrentScreenInHistory: Boolean = true
`keepInHistory`?

2024-12-23 12:57 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
> +     * visible screen in the history or not.
"or not" is redundant when used in conjunction with `whether`. Unless you really-really want to put emphasis on this "or not", which I don't think is the case.

2024-12-23 12:57 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
> +     * @throws IllegalStateException To indicate the illegal state when some
Please explain why this case is an illegal one.

2024-12-23 12:57 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
> +        checkScreenNavigatorIsInitialized()
Let's shorten the name of this method.

2024-12-23 12:57 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
> +            "Cannot close the current screen because this is a bottom-most " +
If possible, let's add something that would allow the devs to identify the currently displayed screen once this exception is raised.

2024-12-23 12:57 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/appshell/Application.kt
> +public class Screens
Why isn't this a part of `AppWindow` API?

The same question applies to `Views` below.

2024-12-23 14:02 UTC, Oleg-Melnik commented on core/build.gradle.kts
> +    implementation(Voyager.navigator)
My current vision is that Voyager's API will be used internally by the Chords UI modules, while Chords will provide a more user-friendly API for navigation. This is because Voyager exposes low-level API, such as stack-like functionality, etc.

2024-12-23 23:28 UTC, dpikhulya reviewed
@Oleg-Melnik Please see my thoughts to consider.

2024-12-23 23:28 UTC, dpikhulya commented on core/src/main/kotlin/io/spine/chords/core/appshell/SignInScreen.kt
> +            onSuccessAuthentication.invoke()
Since `onSuccessAuthentication` is not nullable, I'd rather use just `onSuccessAuthentication()` for conciseness.

2024-12-23 23:28 UTC, dpikhulya commented on core/src/main/kotlin/io/spine/chords/core/appshell/SignInScreen.kt
> +public class SignInScreen(
- Do I understand correctly that so far it's only used internally in the library (instantiated to initialize `AppWindow.signInScreen`), and it's not meant to be overridden or used outside of the library? If so, can we make it `internal`?
- Actually, if it's really a specifics of implementing `AppWindow`, I'd also consider declaring it inside of `AppWindow.kt`, since having it in a separate file, especially the one in the root package, provokes thoughts on its reusability.

2024-12-24 15:20 UTC, Oleg-Melnik commented on core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
> +        keepCurrentScreenInHistory: Boolean = true
This parameter is removed at all.

2024-12-24 16:02 UTC, Oleg-Melnik commented on core/src/main/kotlin/io/spine/chords/core/appshell/Application.kt
> +public class Screens
The `Screens` and `Views` classes have been removed.

2024-12-24 16:13 UTC, armiol requested changes
@Oleg-Melnik see my comments. 

My primary concern is explaining to our end-users that difference that we are trying to establish between "views" and "screens". We mix the interfaces and words in our code right now so that it becomes difficult to comprehend.

2024-12-24 16:13 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/appshell/AppView.kt
> + * The [AppView] implements the [Screen] interface, enabling the use of
Here, it's the same question regarding exposing Voyager API. If `AppView` is `public`, and it acts as a Voyager's `Screen`, then end-users will need Voyager in their classpath. Hence, it must be `api`.

Please correct me if I am wrong.

2024-12-24 16:13 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
> +    internal fun showScreen(screen: Screen) {
Can we shorten it to `show(screen: Screen)`?

2024-12-24 16:13 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
> + * Represents the Sign-In screen in the application.
Let's simplify without this pretentious "Represents":
```
A sign-in screen of the application.
```

2024-12-24 16:13 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/appshell/Application.kt
> +     * Returns the currently selected view.
There should be a place somewhere in the code docs where we explain the difference between a view and a screen. Or telling that this is the same thing (which it is not, as far as we discussed).

Current API of `AppView` and the API of this type are confusing: they have both "show..." methods working with `Screen`s and `currentView` returning `AppView` (which is ALSO as `Screen`).

2024-12-24 16:13 UTC, armiol commented on pom.xml
> +    <version>1.0.0</version>
They have [`1.0.1`](https://mvnrepository.com/artifact/cafe.adriel.voyager/voyager-screenmodel/1.0.1), which I believe is a bugfix release.

2024-12-30 13:46 UTC, armiol approved these changes
@Oleg-Melnik LGTM in general. However, please see my comments.

2024-12-30 13:46 UTC, armiol commented on core/build.gradle.kts
> +    api(Voyager.navigator)
Let's move this to be the first item. It's more logical, because `api`-level dependencies are transitive.

2024-12-30 13:46 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/appshell/AppView.kt
> + * See [AppWindow] on how to select some [AppView] to be displayed.
It would be good to provide the link to some particular method, not just to a type.

2024-12-30 13:46 UTC, armiol commented on core/src/main/kotlin/io/spine/chords/core/appshell/AppWindow.kt
> + * Provides two levels of navigation enabled by the Voyager multiplatform
Let's simplify: 

```
 * Powered by Voyager, provides two levels of navigation:
 *
 * 1.The screen-level navigation. Allows selecting a screen
 * to fill the entire main window.
 *
 * Currently, there is no public API available to display a custom screen.
 * Instead, two screens are predefined: [SignInScreen] and [MainScreen].
 * Please refer to their description for more detail.
 * In the future, more screen implementations may be created.
 *
 * 2. The view-level navigation. Allows selecting an [AppView] to be displayed
 * on the `MainScreen`. 
 * Please refer to [ApplicationUI] <TODO: can we point to the method here?>
 * for details.
```

2024-12-30 17:15 UTC, dpikhulya approved these changes
@Oleg-Melnik LGTM with just a small idea to consider.

2024-12-30 17:15 UTC, dpikhulya commented on core/src/main/kotlin/io/spine/chords/core/appshell/Application.kt
> +    public val currentView: AppView get() = appWindow.currentView
@Oleg-Melnik I think you've considered this, and there probably were some arguments for having the `select()` method separately, but, just in case, I'd like to pinpoint an alternative that might seem more natural if no changes to `select` are planned in the future: 

we could actually replace `select` with turning `currentView` into a mutable property and having the respective functionality in its setter.

2025-01-02 17:13 UTC, merged